# 最后更新时间：2024-1-11 12:42

name: Fork Filter lists

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  
jobs:
  Fork-FLITER-list:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0
    
    - name: Fork ACL4SSR Rules
      run: |
        mkdir -p Rules
        git clone -b master https://github.com/ACL4SSR/ACL4SSR.git ACL4SSR_Tmp
        find ACL4SSR_Tmp/Clash -type f -name '*.list' -exec cp {} Rules \;
        rm -rf ACL4SSR_Tmp

      # 适配 QuantumultX 规则
    - name: Edit QuantumultX/Rules
      run: |
        cd Rules
        find . -type f -name '*.list' -print0 | while IFS= read -r -d $'\0' file; do
          if [ -f "$file" ]; then
            # 修改, 为,
            sed -i 's/, /,/g' "$file"
            # 修改DOMAIN为HOST
            sed -i -e 's/DOMAIN,/HOST,/g' -e 's/DOMAIN-/HOST-/g' "$file"
            # 修改IP-CIDR6为IP6-CIDR
            sed -i 's/IP-CIDR6,/IP6-CIDR,/g' "$file"
            # 删除no-resolve
            sed -i 's/,no-resolve//g' "$file"
            # 删除extended-matching
            sed -i 's/,extended-matching//g' "$file"
            # 注释不支持的规则
            sed -i -e '/\(OR\|AND\|NOT\|PROCESS-NAME\|URL-REGEX\),/ s/^/#/' "$file"
            # 删除" //" 以及后面的所有字符
            sed -i 's| \{1,\}//.*$||' "$file"
            # 在非注释后添加PROXY
            awk '!/\/\/|#|,PROXY|,DIRECT|,REJECT|^ *$/ {print $0",PROXY"; next} {print}' "$file" > tmpfile
            mv tmpfile "$file"
          else
            echo "$file not found."
          fi
        done

      # 适配 QuantumultX 规则
    - name: Edit QuantumultX/Rules/Ads
      run: |
        cd Rules
        for file in Ban*.list MIUIPrivacy.list PrivateTracker.list; do
          if [ "$file" != "UnBan.list" ]; then
            # 修改PROXY为REJECT
            sed -i 's/,PROXY/,REJECT/g' "$file"
          else
            echo "$file not found."
          fi
        done

      # 适配 QuantumultX 规则
    - name: Edit QuantumultX/Rules/CN
      run: |
        cd Rules
        for file in AccelerateDirectSites.list Bilibili.list WeChat.list China*.list GoogleCN.list UnBan.list 360.list 4399.list 58.list Apple.list Baidu.list ByteDance.list CN.list Douyu.lsit CCTV.list Download.list Iqiyi.list JD.list LeTV.list LocalAreaNetwork.list MI.list Meitu.list NetEase*.list PDD.list PPTVPPLive.list PublicDirectCDN.list Sina.list SohuSogo.list SteamCN.list TapTap.list Tencent*.list Vip.list Ximalaya.list Xunlei.list YYeTs.list Youku.list Wechat.list; do
          if [ -f "$file" ]; then
            # 修改PROXY为DIRECT
            sed -i 's/,PROXY/,DIRECT/g' "$file"
          else
            echo "$file not found."
          fi
        done

    - name: Add and Commits
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
